; This "include" file can be imported into assembly projects.

zsm_init_engine  = $A000
zsm_tick         = $A003
zsm_play         = $A006
zsm_stop         = $A009
zsm_rewind       = $A00C
zsm_close        = $A00F

zsm_setbank      = $A01B
zsm_setmem       = $A01E
zsm_setatten     = $A021
zsm_setcb        = $A024
zsm_clearcb      = $A027
zsm_getstate     = $A02A
zsm_setrate      = $A02D
zsm_getrate      = $A030
zsm_setloop      = $A033
zsm_opmatten     = $A036
zsm_psgatten     = $A039
zsm_pcmatten     = $A03C
zsm_set_int_rate = $A03F

zcm_setbank      = $A048
zcm_setmem       = $A04B
zcm_play         = $A04E
zcm_stop         = $A051
zsmkit_setisr    = $A054
zsmkit_clearisr  = $A057
